[env:uno_ada]
platform = atmelavr
board = uno
framework = arduino
lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ILI9341
build_flags = -D USE_ADAFRUIT_DISPLAY

[env:due_tft_espi]
platform = atmelsam
board = due
framework = arduino
lib_deps =
  bodmer/TFT_eSPI
build_flags = -D USE_TFT_ESPI_DISPLAY -fno-strict-aliasing